### ISSUE TITLE
The plugin doesn't respect 'Default sort order' property of the attributes.

### ISSUE THREAD

**Issue by Drugoy** [isabelc/WooCommerce-Show-Attributes#8]
The plugin ignores the option 'Products > Attributes > Default sort order'.

WordPress 4.4.2
WooCommerce 2.5.2
WooCommerce Show Attributes 1.4.2

**Comment by isabelc** [comment]
It obeys the sort order. If you select "Custom Ordering," then after you save that, you have to "Configure terms" and drag and drop the terms in the order that you want them.
